pool:
  vmImage: 'Ubuntu-18.04'

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - .editorconfig
    - LICENSE
    - README.md

pr:
  branches:
    include: ['*']
  paths:
    exclude:
    - .editorconfig
    - LICENSE
    - README.md

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

steps:

- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.300'
  inputs:
    packageType: sdk
    version: 3.1.300

- bash: |
    dotnet tool install --global Cake.Tool --version 0.35.0
  displayName: 'Install "Cake.Tool" .NET Core global tool'

- bash: |
    export PATH="$PATH:$HOME/.dotnet/tools"
    dotnet cake build.cake --bootstrap
    dotnet cake build.cake --pack
  displayName: 'Build'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '*.trx'
    searchFolder: '$(System.DefaultWorkingDirectory)/artifacts/tests-results'
  condition: succeededOrFailed()
  displayName: 'Publish Test Results'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Global Tool'
  inputs:
    PathtoPublish: artifacts/packages
    ArtifactName: global-tool

- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'dotnet-fwpf'
    packagesToPush: artifacts/packages/**/*.nupkg
    versioningScheme: byEnvVar
    versionEnvVar: $(NuGetVersion)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
